import {MediaConfig} from './index';
import {Parsable} from '@microsoft/kiota-abstractions';

export interface AppHostedMediaConfig extends MediaConfig, Partial<Parsable> {
    /** The media configuration blob generated by smart media agent. */
    blob?: string;
}
