import {AdditionalDataHolder, Parsable} from '@microsoft/kiota-abstractions';

export interface ChangeNotificationEncryptedContent extends Partial<AdditionalDataHolder>, Partial<Parsable> {
    /** Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well. */
    additionalData?: Record<string, unknown>;
    /** Base64-encoded encrypted data that produces a full resource respresented as JSON. The data has been encrypted with the provided dataKey using an AES/CBC/PKCS5PADDING cipher suite. */
    data?: string;
    /** Base64-encoded symmetric key generated by Microsoft Graph to encrypt the data value and to generate the data signature. This key is encrypted with the certificate public key that was provided during the subscription. It must be decrypted with the certificate private key before it can be used to decrypt the data or verify the signature. This key has been encrypted with the following cipher suite: RSA/ECB/OAEPWithSHA1AndMGF1Padding. */
    dataKey?: string;
    /** Base64-encoded HMAC-SHA256 hash of the data for validation purposes. */
    dataSignature?: string;
    /** ID of the certificate used to encrypt the dataKey. */
    encryptionCertificateId?: string;
    /** Hexadecimal representation of the thumbprint of the certificate used to encrypt the dataKey. */
    encryptionCertificateThumbprint?: string;
    /** The OdataType property */
    odataType?: string;
}
