import {DefenderCloudBlockLevelType} from './defenderCloudBlockLevelType';
import {DefenderMonitorFileActivity} from './defenderMonitorFileActivity';
import {DefenderPromptForSampleSubmission} from './defenderPromptForSampleSubmission';
import {DefenderScanType} from './defenderScanType';
import {deserializeIntoDefenderDetectedMalwareActions} from './deserializeIntoDefenderDetectedMalwareActions';
import {deserializeIntoDeviceConfiguration} from './deserializeIntoDeviceConfiguration';
import {deserializeIntoEdgeSearchEngineBase} from './deserializeIntoEdgeSearchEngineBase';
import {deserializeIntoWindows10NetworkProxyServer} from './deserializeIntoWindows10NetworkProxyServer';
import {DiagnosticDataSubmissionMode} from './diagnosticDataSubmissionMode';
import {EdgeCookiePolicy} from './edgeCookiePolicy';
import {Windows10GeneralConfiguration} from './index';
import {RequiredPasswordType} from './requiredPasswordType';
import {SafeSearchFilterType} from './safeSearchFilterType';
import {StateManagementSetting} from './stateManagementSetting';
import {VisibilitySetting} from './visibilitySetting';
import {WeeklySchedule} from './weeklySchedule';
import {WindowsSpotlightEnablementSettings} from './windowsSpotlightEnablementSettings';
import {WindowsStartMenuAppListVisibilityType} from './windowsStartMenuAppListVisibilityType';
import {WindowsStartMenuModeType} from './windowsStartMenuModeType';
import {Parsable, ParseNode, SerializationWriter, TimeOnly} from '@microsoft/kiota-abstractions';

export function deserializeIntoWindows10GeneralConfiguration(windows10GeneralConfiguration: Windows10GeneralConfiguration | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoDeviceConfiguration(windows10GeneralConfiguration),
        "accountsBlockAddingNonMicrosoftAccountEmail": n => { windows10GeneralConfiguration.accountsBlockAddingNonMicrosoftAccountEmail = n.getBooleanValue() as any ; },
        "antiTheftModeBlocked": n => { windows10GeneralConfiguration.antiTheftModeBlocked = n.getBooleanValue() as any ; },
        "appsAllowTrustedAppsSideloading": n => { windows10GeneralConfiguration.appsAllowTrustedAppsSideloading = n.getEnumValue<StateManagementSetting>(StateManagementSetting) as any ; },
        "appsBlockWindowsStoreOriginatedApps": n => { windows10GeneralConfiguration.appsBlockWindowsStoreOriginatedApps = n.getBooleanValue() as any ; },
        "bluetoothAllowedServices": n => { windows10GeneralConfiguration.bluetoothAllowedServices = n.getCollectionOfPrimitiveValues<string>() as any ; },
        "bluetoothBlockAdvertising": n => { windows10GeneralConfiguration.bluetoothBlockAdvertising = n.getBooleanValue() as any ; },
        "bluetoothBlockDiscoverableMode": n => { windows10GeneralConfiguration.bluetoothBlockDiscoverableMode = n.getBooleanValue() as any ; },
        "bluetoothBlocked": n => { windows10GeneralConfiguration.bluetoothBlocked = n.getBooleanValue() as any ; },
        "bluetoothBlockPrePairing": n => { windows10GeneralConfiguration.bluetoothBlockPrePairing = n.getBooleanValue() as any ; },
        "cameraBlocked": n => { windows10GeneralConfiguration.cameraBlocked = n.getBooleanValue() as any ; },
        "cellularBlockDataWhenRoaming": n => { windows10GeneralConfiguration.cellularBlockDataWhenRoaming = n.getBooleanValue() as any ; },
        "cellularBlockVpn": n => { windows10GeneralConfiguration.cellularBlockVpn = n.getBooleanValue() as any ; },
        "cellularBlockVpnWhenRoaming": n => { windows10GeneralConfiguration.cellularBlockVpnWhenRoaming = n.getBooleanValue() as any ; },
        "certificatesBlockManualRootCertificateInstallation": n => { windows10GeneralConfiguration.certificatesBlockManualRootCertificateInstallation = n.getBooleanValue() as any ; },
        "connectedDevicesServiceBlocked": n => { windows10GeneralConfiguration.connectedDevicesServiceBlocked = n.getBooleanValue() as any ; },
        "copyPasteBlocked": n => { windows10GeneralConfiguration.copyPasteBlocked = n.getBooleanValue() as any ; },
        "cortanaBlocked": n => { windows10GeneralConfiguration.cortanaBlocked = n.getBooleanValue() as any ; },
        "defenderBlockEndUserAccess": n => { windows10GeneralConfiguration.defenderBlockEndUserAccess = n.getBooleanValue() as any ; },
        "defenderCloudBlockLevel": n => { windows10GeneralConfiguration.defenderCloudBlockLevel = n.getEnumValue<DefenderCloudBlockLevelType>(DefenderCloudBlockLevelType) as any ; },
        "defenderDaysBeforeDeletingQuarantinedMalware": n => { windows10GeneralConfiguration.defenderDaysBeforeDeletingQuarantinedMalware = n.getNumberValue() as any ; },
        "defenderDetectedMalwareActions": n => { windows10GeneralConfiguration.defenderDetectedMalwareActions = n.getObject(deserializeIntoDefenderDetectedMalwareActions) as any ; },
        "defenderFileExtensionsToExclude": n => { windows10GeneralConfiguration.defenderFileExtensionsToExclude = n.getCollectionOfPrimitiveValues<string>() as any ; },
        "defenderFilesAndFoldersToExclude": n => { windows10GeneralConfiguration.defenderFilesAndFoldersToExclude = n.getCollectionOfPrimitiveValues<string>() as any ; },
        "defenderMonitorFileActivity": n => { windows10GeneralConfiguration.defenderMonitorFileActivity = n.getEnumValue<DefenderMonitorFileActivity>(DefenderMonitorFileActivity) as any ; },
        "defenderProcessesToExclude": n => { windows10GeneralConfiguration.defenderProcessesToExclude = n.getCollectionOfPrimitiveValues<string>() as any ; },
        "defenderPromptForSampleSubmission": n => { windows10GeneralConfiguration.defenderPromptForSampleSubmission = n.getEnumValue<DefenderPromptForSampleSubmission>(DefenderPromptForSampleSubmission) as any ; },
        "defenderRequireBehaviorMonitoring": n => { windows10GeneralConfiguration.defenderRequireBehaviorMonitoring = n.getBooleanValue() as any ; },
        "defenderRequireCloudProtection": n => { windows10GeneralConfiguration.defenderRequireCloudProtection = n.getBooleanValue() as any ; },
        "defenderRequireNetworkInspectionSystem": n => { windows10GeneralConfiguration.defenderRequireNetworkInspectionSystem = n.getBooleanValue() as any ; },
        "defenderRequireRealTimeMonitoring": n => { windows10GeneralConfiguration.defenderRequireRealTimeMonitoring = n.getBooleanValue() as any ; },
        "defenderScanArchiveFiles": n => { windows10GeneralConfiguration.defenderScanArchiveFiles = n.getBooleanValue() as any ; },
        "defenderScanDownloads": n => { windows10GeneralConfiguration.defenderScanDownloads = n.getBooleanValue() as any ; },
        "defenderScanIncomingMail": n => { windows10GeneralConfiguration.defenderScanIncomingMail = n.getBooleanValue() as any ; },
        "defenderScanMappedNetworkDrivesDuringFullScan": n => { windows10GeneralConfiguration.defenderScanMappedNetworkDrivesDuringFullScan = n.getBooleanValue() as any ; },
        "defenderScanMaxCpu": n => { windows10GeneralConfiguration.defenderScanMaxCpu = n.getNumberValue() as any ; },
        "defenderScanNetworkFiles": n => { windows10GeneralConfiguration.defenderScanNetworkFiles = n.getBooleanValue() as any ; },
        "defenderScanRemovableDrivesDuringFullScan": n => { windows10GeneralConfiguration.defenderScanRemovableDrivesDuringFullScan = n.getBooleanValue() as any ; },
        "defenderScanScriptsLoadedInInternetExplorer": n => { windows10GeneralConfiguration.defenderScanScriptsLoadedInInternetExplorer = n.getBooleanValue() as any ; },
        "defenderScanType": n => { windows10GeneralConfiguration.defenderScanType = n.getEnumValue<DefenderScanType>(DefenderScanType) as any ; },
        "defenderScheduledQuickScanTime": n => { windows10GeneralConfiguration.defenderScheduledQuickScanTime = n.getTimeOnlyValue() as any ; },
        "defenderScheduledScanTime": n => { windows10GeneralConfiguration.defenderScheduledScanTime = n.getTimeOnlyValue() as any ; },
        "defenderSignatureUpdateIntervalInHours": n => { windows10GeneralConfiguration.defenderSignatureUpdateIntervalInHours = n.getNumberValue() as any ; },
        "defenderSystemScanSchedule": n => { windows10GeneralConfiguration.defenderSystemScanSchedule = n.getEnumValue<WeeklySchedule>(WeeklySchedule) as any ; },
        "developerUnlockSetting": n => { windows10GeneralConfiguration.developerUnlockSetting = n.getEnumValue<StateManagementSetting>(StateManagementSetting) as any ; },
        "deviceManagementBlockFactoryResetOnMobile": n => { windows10GeneralConfiguration.deviceManagementBlockFactoryResetOnMobile = n.getBooleanValue() as any ; },
        "deviceManagementBlockManualUnenroll": n => { windows10GeneralConfiguration.deviceManagementBlockManualUnenroll = n.getBooleanValue() as any ; },
        "diagnosticsDataSubmissionMode": n => { windows10GeneralConfiguration.diagnosticsDataSubmissionMode = n.getEnumValue<DiagnosticDataSubmissionMode>(DiagnosticDataSubmissionMode) as any ; },
        "edgeAllowStartPagesModification": n => { windows10GeneralConfiguration.edgeAllowStartPagesModification = n.getBooleanValue() as any ; },
        "edgeBlockAccessToAboutFlags": n => { windows10GeneralConfiguration.edgeBlockAccessToAboutFlags = n.getBooleanValue() as any ; },
        "edgeBlockAddressBarDropdown": n => { windows10GeneralConfiguration.edgeBlockAddressBarDropdown = n.getBooleanValue() as any ; },
        "edgeBlockAutofill": n => { windows10GeneralConfiguration.edgeBlockAutofill = n.getBooleanValue() as any ; },
        "edgeBlockCompatibilityList": n => { windows10GeneralConfiguration.edgeBlockCompatibilityList = n.getBooleanValue() as any ; },
        "edgeBlockDeveloperTools": n => { windows10GeneralConfiguration.edgeBlockDeveloperTools = n.getBooleanValue() as any ; },
        "edgeBlocked": n => { windows10GeneralConfiguration.edgeBlocked = n.getBooleanValue() as any ; },
        "edgeBlockExtensions": n => { windows10GeneralConfiguration.edgeBlockExtensions = n.getBooleanValue() as any ; },
        "edgeBlockInPrivateBrowsing": n => { windows10GeneralConfiguration.edgeBlockInPrivateBrowsing = n.getBooleanValue() as any ; },
        "edgeBlockJavaScript": n => { windows10GeneralConfiguration.edgeBlockJavaScript = n.getBooleanValue() as any ; },
        "edgeBlockLiveTileDataCollection": n => { windows10GeneralConfiguration.edgeBlockLiveTileDataCollection = n.getBooleanValue() as any ; },
        "edgeBlockPasswordManager": n => { windows10GeneralConfiguration.edgeBlockPasswordManager = n.getBooleanValue() as any ; },
        "edgeBlockPopups": n => { windows10GeneralConfiguration.edgeBlockPopups = n.getBooleanValue() as any ; },
        "edgeBlockSearchSuggestions": n => { windows10GeneralConfiguration.edgeBlockSearchSuggestions = n.getBooleanValue() as any ; },
        "edgeBlockSendingDoNotTrackHeader": n => { windows10GeneralConfiguration.edgeBlockSendingDoNotTrackHeader = n.getBooleanValue() as any ; },
        "edgeBlockSendingIntranetTrafficToInternetExplorer": n => { windows10GeneralConfiguration.edgeBlockSendingIntranetTrafficToInternetExplorer = n.getBooleanValue() as any ; },
        "edgeClearBrowsingDataOnExit": n => { windows10GeneralConfiguration.edgeClearBrowsingDataOnExit = n.getBooleanValue() as any ; },
        "edgeCookiePolicy": n => { windows10GeneralConfiguration.edgeCookiePolicy = n.getEnumValue<EdgeCookiePolicy>(EdgeCookiePolicy) as any ; },
        "edgeDisableFirstRunPage": n => { windows10GeneralConfiguration.edgeDisableFirstRunPage = n.getBooleanValue() as any ; },
        "edgeEnterpriseModeSiteListLocation": n => { windows10GeneralConfiguration.edgeEnterpriseModeSiteListLocation = n.getStringValue() as any ; },
        "edgeFirstRunUrl": n => { windows10GeneralConfiguration.edgeFirstRunUrl = n.getStringValue() as any ; },
        "edgeHomepageUrls": n => { windows10GeneralConfiguration.edgeHomepageUrls = n.getCollectionOfPrimitiveValues<string>() as any ; },
        "edgeRequireSmartScreen": n => { windows10GeneralConfiguration.edgeRequireSmartScreen = n.getBooleanValue() as any ; },
        "edgeSearchEngine": n => { windows10GeneralConfiguration.edgeSearchEngine = n.getObject(deserializeIntoEdgeSearchEngineBase) as any ; },
        "edgeSendIntranetTrafficToInternetExplorer": n => { windows10GeneralConfiguration.edgeSendIntranetTrafficToInternetExplorer = n.getBooleanValue() as any ; },
        "edgeSyncFavoritesWithInternetExplorer": n => { windows10GeneralConfiguration.edgeSyncFavoritesWithInternetExplorer = n.getBooleanValue() as any ; },
        "enterpriseCloudPrintDiscoveryEndPoint": n => { windows10GeneralConfiguration.enterpriseCloudPrintDiscoveryEndPoint = n.getStringValue() as any ; },
        "enterpriseCloudPrintDiscoveryMaxLimit": n => { windows10GeneralConfiguration.enterpriseCloudPrintDiscoveryMaxLimit = n.getNumberValue() as any ; },
        "enterpriseCloudPrintMopriaDiscoveryResourceIdentifier": n => { windows10GeneralConfiguration.enterpriseCloudPrintMopriaDiscoveryResourceIdentifier = n.getStringValue() as any ; },
        "enterpriseCloudPrintOAuthAuthority": n => { windows10GeneralConfiguration.enterpriseCloudPrintOAuthAuthority = n.getStringValue() as any ; },
        "enterpriseCloudPrintOAuthClientIdentifier": n => { windows10GeneralConfiguration.enterpriseCloudPrintOAuthClientIdentifier = n.getStringValue() as any ; },
        "enterpriseCloudPrintResourceIdentifier": n => { windows10GeneralConfiguration.enterpriseCloudPrintResourceIdentifier = n.getStringValue() as any ; },
        "experienceBlockDeviceDiscovery": n => { windows10GeneralConfiguration.experienceBlockDeviceDiscovery = n.getBooleanValue() as any ; },
        "experienceBlockErrorDialogWhenNoSIM": n => { windows10GeneralConfiguration.experienceBlockErrorDialogWhenNoSIM = n.getBooleanValue() as any ; },
        "experienceBlockTaskSwitcher": n => { windows10GeneralConfiguration.experienceBlockTaskSwitcher = n.getBooleanValue() as any ; },
        "gameDvrBlocked": n => { windows10GeneralConfiguration.gameDvrBlocked = n.getBooleanValue() as any ; },
        "internetSharingBlocked": n => { windows10GeneralConfiguration.internetSharingBlocked = n.getBooleanValue() as any ; },
        "locationServicesBlocked": n => { windows10GeneralConfiguration.locationServicesBlocked = n.getBooleanValue() as any ; },
        "lockScreenAllowTimeoutConfiguration": n => { windows10GeneralConfiguration.lockScreenAllowTimeoutConfiguration = n.getBooleanValue() as any ; },
        "lockScreenBlockActionCenterNotifications": n => { windows10GeneralConfiguration.lockScreenBlockActionCenterNotifications = n.getBooleanValue() as any ; },
        "lockScreenBlockCortana": n => { windows10GeneralConfiguration.lockScreenBlockCortana = n.getBooleanValue() as any ; },
        "lockScreenBlockToastNotifications": n => { windows10GeneralConfiguration.lockScreenBlockToastNotifications = n.getBooleanValue() as any ; },
        "lockScreenTimeoutInSeconds": n => { windows10GeneralConfiguration.lockScreenTimeoutInSeconds = n.getNumberValue() as any ; },
        "logonBlockFastUserSwitching": n => { windows10GeneralConfiguration.logonBlockFastUserSwitching = n.getBooleanValue() as any ; },
        "microsoftAccountBlocked": n => { windows10GeneralConfiguration.microsoftAccountBlocked = n.getBooleanValue() as any ; },
        "microsoftAccountBlockSettingsSync": n => { windows10GeneralConfiguration.microsoftAccountBlockSettingsSync = n.getBooleanValue() as any ; },
        "networkProxyApplySettingsDeviceWide": n => { windows10GeneralConfiguration.networkProxyApplySettingsDeviceWide = n.getBooleanValue() as any ; },
        "networkProxyAutomaticConfigurationUrl": n => { windows10GeneralConfiguration.networkProxyAutomaticConfigurationUrl = n.getStringValue() as any ; },
        "networkProxyDisableAutoDetect": n => { windows10GeneralConfiguration.networkProxyDisableAutoDetect = n.getBooleanValue() as any ; },
        "networkProxyServer": n => { windows10GeneralConfiguration.networkProxyServer = n.getObject(deserializeIntoWindows10NetworkProxyServer) as any ; },
        "nfcBlocked": n => { windows10GeneralConfiguration.nfcBlocked = n.getBooleanValue() as any ; },
        "oneDriveDisableFileSync": n => { windows10GeneralConfiguration.oneDriveDisableFileSync = n.getBooleanValue() as any ; },
        "passwordBlockSimple": n => { windows10GeneralConfiguration.passwordBlockSimple = n.getBooleanValue() as any ; },
        "passwordExpirationDays": n => { windows10GeneralConfiguration.passwordExpirationDays = n.getNumberValue() as any ; },
        "passwordMinimumCharacterSetCount": n => { windows10GeneralConfiguration.passwordMinimumCharacterSetCount = n.getNumberValue() as any ; },
        "passwordMinimumLength": n => { windows10GeneralConfiguration.passwordMinimumLength = n.getNumberValue() as any ; },
        "passwordMinutesOfInactivityBeforeScreenTimeout": n => { windows10GeneralConfiguration.passwordMinutesOfInactivityBeforeScreenTimeout = n.getNumberValue() as any ; },
        "passwordPreviousPasswordBlockCount": n => { windows10GeneralConfiguration.passwordPreviousPasswordBlockCount = n.getNumberValue() as any ; },
        "passwordRequired": n => { windows10GeneralConfiguration.passwordRequired = n.getBooleanValue() as any ; },
        "passwordRequiredType": n => { windows10GeneralConfiguration.passwordRequiredType = n.getEnumValue<RequiredPasswordType>(RequiredPasswordType) as any ; },
        "passwordRequireWhenResumeFromIdleState": n => { windows10GeneralConfiguration.passwordRequireWhenResumeFromIdleState = n.getBooleanValue() as any ; },
        "passwordSignInFailureCountBeforeFactoryReset": n => { windows10GeneralConfiguration.passwordSignInFailureCountBeforeFactoryReset = n.getNumberValue() as any ; },
        "personalizationDesktopImageUrl": n => { windows10GeneralConfiguration.personalizationDesktopImageUrl = n.getStringValue() as any ; },
        "personalizationLockScreenImageUrl": n => { windows10GeneralConfiguration.personalizationLockScreenImageUrl = n.getStringValue() as any ; },
        "privacyAdvertisingId": n => { windows10GeneralConfiguration.privacyAdvertisingId = n.getEnumValue<StateManagementSetting>(StateManagementSetting) as any ; },
        "privacyAutoAcceptPairingAndConsentPrompts": n => { windows10GeneralConfiguration.privacyAutoAcceptPairingAndConsentPrompts = n.getBooleanValue() as any ; },
        "privacyBlockInputPersonalization": n => { windows10GeneralConfiguration.privacyBlockInputPersonalization = n.getBooleanValue() as any ; },
        "resetProtectionModeBlocked": n => { windows10GeneralConfiguration.resetProtectionModeBlocked = n.getBooleanValue() as any ; },
        "safeSearchFilter": n => { windows10GeneralConfiguration.safeSearchFilter = n.getEnumValue<SafeSearchFilterType>(SafeSearchFilterType) as any ; },
        "screenCaptureBlocked": n => { windows10GeneralConfiguration.screenCaptureBlocked = n.getBooleanValue() as any ; },
        "searchBlockDiacritics": n => { windows10GeneralConfiguration.searchBlockDiacritics = n.getBooleanValue() as any ; },
        "searchDisableAutoLanguageDetection": n => { windows10GeneralConfiguration.searchDisableAutoLanguageDetection = n.getBooleanValue() as any ; },
        "searchDisableIndexerBackoff": n => { windows10GeneralConfiguration.searchDisableIndexerBackoff = n.getBooleanValue() as any ; },
        "searchDisableIndexingEncryptedItems": n => { windows10GeneralConfiguration.searchDisableIndexingEncryptedItems = n.getBooleanValue() as any ; },
        "searchDisableIndexingRemovableDrive": n => { windows10GeneralConfiguration.searchDisableIndexingRemovableDrive = n.getBooleanValue() as any ; },
        "searchEnableAutomaticIndexSizeManangement": n => { windows10GeneralConfiguration.searchEnableAutomaticIndexSizeManangement = n.getBooleanValue() as any ; },
        "searchEnableRemoteQueries": n => { windows10GeneralConfiguration.searchEnableRemoteQueries = n.getBooleanValue() as any ; },
        "settingsBlockAccountsPage": n => { windows10GeneralConfiguration.settingsBlockAccountsPage = n.getBooleanValue() as any ; },
        "settingsBlockAddProvisioningPackage": n => { windows10GeneralConfiguration.settingsBlockAddProvisioningPackage = n.getBooleanValue() as any ; },
        "settingsBlockAppsPage": n => { windows10GeneralConfiguration.settingsBlockAppsPage = n.getBooleanValue() as any ; },
        "settingsBlockChangeLanguage": n => { windows10GeneralConfiguration.settingsBlockChangeLanguage = n.getBooleanValue() as any ; },
        "settingsBlockChangePowerSleep": n => { windows10GeneralConfiguration.settingsBlockChangePowerSleep = n.getBooleanValue() as any ; },
        "settingsBlockChangeRegion": n => { windows10GeneralConfiguration.settingsBlockChangeRegion = n.getBooleanValue() as any ; },
        "settingsBlockChangeSystemTime": n => { windows10GeneralConfiguration.settingsBlockChangeSystemTime = n.getBooleanValue() as any ; },
        "settingsBlockDevicesPage": n => { windows10GeneralConfiguration.settingsBlockDevicesPage = n.getBooleanValue() as any ; },
        "settingsBlockEaseOfAccessPage": n => { windows10GeneralConfiguration.settingsBlockEaseOfAccessPage = n.getBooleanValue() as any ; },
        "settingsBlockEditDeviceName": n => { windows10GeneralConfiguration.settingsBlockEditDeviceName = n.getBooleanValue() as any ; },
        "settingsBlockGamingPage": n => { windows10GeneralConfiguration.settingsBlockGamingPage = n.getBooleanValue() as any ; },
        "settingsBlockNetworkInternetPage": n => { windows10GeneralConfiguration.settingsBlockNetworkInternetPage = n.getBooleanValue() as any ; },
        "settingsBlockPersonalizationPage": n => { windows10GeneralConfiguration.settingsBlockPersonalizationPage = n.getBooleanValue() as any ; },
        "settingsBlockPrivacyPage": n => { windows10GeneralConfiguration.settingsBlockPrivacyPage = n.getBooleanValue() as any ; },
        "settingsBlockRemoveProvisioningPackage": n => { windows10GeneralConfiguration.settingsBlockRemoveProvisioningPackage = n.getBooleanValue() as any ; },
        "settingsBlockSettingsApp": n => { windows10GeneralConfiguration.settingsBlockSettingsApp = n.getBooleanValue() as any ; },
        "settingsBlockSystemPage": n => { windows10GeneralConfiguration.settingsBlockSystemPage = n.getBooleanValue() as any ; },
        "settingsBlockTimeLanguagePage": n => { windows10GeneralConfiguration.settingsBlockTimeLanguagePage = n.getBooleanValue() as any ; },
        "settingsBlockUpdateSecurityPage": n => { windows10GeneralConfiguration.settingsBlockUpdateSecurityPage = n.getBooleanValue() as any ; },
        "sharedUserAppDataAllowed": n => { windows10GeneralConfiguration.sharedUserAppDataAllowed = n.getBooleanValue() as any ; },
        "smartScreenBlockPromptOverride": n => { windows10GeneralConfiguration.smartScreenBlockPromptOverride = n.getBooleanValue() as any ; },
        "smartScreenBlockPromptOverrideForFiles": n => { windows10GeneralConfiguration.smartScreenBlockPromptOverrideForFiles = n.getBooleanValue() as any ; },
        "smartScreenEnableAppInstallControl": n => { windows10GeneralConfiguration.smartScreenEnableAppInstallControl = n.getBooleanValue() as any ; },
        "startBlockUnpinningAppsFromTaskbar": n => { windows10GeneralConfiguration.startBlockUnpinningAppsFromTaskbar = n.getBooleanValue() as any ; },
        "startMenuAppListVisibility": n => { windows10GeneralConfiguration.startMenuAppListVisibility = n.getEnumValue<WindowsStartMenuAppListVisibilityType>(WindowsStartMenuAppListVisibilityType) as any ; },
        "startMenuHideChangeAccountSettings": n => { windows10GeneralConfiguration.startMenuHideChangeAccountSettings = n.getBooleanValue() as any ; },
        "startMenuHideFrequentlyUsedApps": n => { windows10GeneralConfiguration.startMenuHideFrequentlyUsedApps = n.getBooleanValue() as any ; },
        "startMenuHideHibernate": n => { windows10GeneralConfiguration.startMenuHideHibernate = n.getBooleanValue() as any ; },
        "startMenuHideLock": n => { windows10GeneralConfiguration.startMenuHideLock = n.getBooleanValue() as any ; },
        "startMenuHidePowerButton": n => { windows10GeneralConfiguration.startMenuHidePowerButton = n.getBooleanValue() as any ; },
        "startMenuHideRecentJumpLists": n => { windows10GeneralConfiguration.startMenuHideRecentJumpLists = n.getBooleanValue() as any ; },
        "startMenuHideRecentlyAddedApps": n => { windows10GeneralConfiguration.startMenuHideRecentlyAddedApps = n.getBooleanValue() as any ; },
        "startMenuHideRestartOptions": n => { windows10GeneralConfiguration.startMenuHideRestartOptions = n.getBooleanValue() as any ; },
        "startMenuHideShutDown": n => { windows10GeneralConfiguration.startMenuHideShutDown = n.getBooleanValue() as any ; },
        "startMenuHideSignOut": n => { windows10GeneralConfiguration.startMenuHideSignOut = n.getBooleanValue() as any ; },
        "startMenuHideSleep": n => { windows10GeneralConfiguration.startMenuHideSleep = n.getBooleanValue() as any ; },
        "startMenuHideSwitchAccount": n => { windows10GeneralConfiguration.startMenuHideSwitchAccount = n.getBooleanValue() as any ; },
        "startMenuHideUserTile": n => { windows10GeneralConfiguration.startMenuHideUserTile = n.getBooleanValue() as any ; },
        "startMenuLayoutEdgeAssetsXml": n => { windows10GeneralConfiguration.startMenuLayoutEdgeAssetsXml = n.getStringValue() as any ; },
        "startMenuLayoutXml": n => { windows10GeneralConfiguration.startMenuLayoutXml = n.getStringValue() as any ; },
        "startMenuMode": n => { windows10GeneralConfiguration.startMenuMode = n.getEnumValue<WindowsStartMenuModeType>(WindowsStartMenuModeType) as any ; },
        "startMenuPinnedFolderDocuments": n => { windows10GeneralConfiguration.startMenuPinnedFolderDocuments = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderDownloads": n => { windows10GeneralConfiguration.startMenuPinnedFolderDownloads = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderFileExplorer": n => { windows10GeneralConfiguration.startMenuPinnedFolderFileExplorer = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderHomeGroup": n => { windows10GeneralConfiguration.startMenuPinnedFolderHomeGroup = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderMusic": n => { windows10GeneralConfiguration.startMenuPinnedFolderMusic = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderNetwork": n => { windows10GeneralConfiguration.startMenuPinnedFolderNetwork = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderPersonalFolder": n => { windows10GeneralConfiguration.startMenuPinnedFolderPersonalFolder = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderPictures": n => { windows10GeneralConfiguration.startMenuPinnedFolderPictures = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderSettings": n => { windows10GeneralConfiguration.startMenuPinnedFolderSettings = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "startMenuPinnedFolderVideos": n => { windows10GeneralConfiguration.startMenuPinnedFolderVideos = n.getEnumValue<VisibilitySetting>(VisibilitySetting) as any ; },
        "storageBlockRemovableStorage": n => { windows10GeneralConfiguration.storageBlockRemovableStorage = n.getBooleanValue() as any ; },
        "storageRequireMobileDeviceEncryption": n => { windows10GeneralConfiguration.storageRequireMobileDeviceEncryption = n.getBooleanValue() as any ; },
        "storageRestrictAppDataToSystemVolume": n => { windows10GeneralConfiguration.storageRestrictAppDataToSystemVolume = n.getBooleanValue() as any ; },
        "storageRestrictAppInstallToSystemVolume": n => { windows10GeneralConfiguration.storageRestrictAppInstallToSystemVolume = n.getBooleanValue() as any ; },
        "tenantLockdownRequireNetworkDuringOutOfBoxExperience": n => { windows10GeneralConfiguration.tenantLockdownRequireNetworkDuringOutOfBoxExperience = n.getBooleanValue() as any ; },
        "usbBlocked": n => { windows10GeneralConfiguration.usbBlocked = n.getBooleanValue() as any ; },
        "voiceRecordingBlocked": n => { windows10GeneralConfiguration.voiceRecordingBlocked = n.getBooleanValue() as any ; },
        "webRtcBlockLocalhostIpAddress": n => { windows10GeneralConfiguration.webRtcBlockLocalhostIpAddress = n.getBooleanValue() as any ; },
        "wiFiBlockAutomaticConnectHotspots": n => { windows10GeneralConfiguration.wiFiBlockAutomaticConnectHotspots = n.getBooleanValue() as any ; },
        "wiFiBlocked": n => { windows10GeneralConfiguration.wiFiBlocked = n.getBooleanValue() as any ; },
        "wiFiBlockManualConfiguration": n => { windows10GeneralConfiguration.wiFiBlockManualConfiguration = n.getBooleanValue() as any ; },
        "wiFiScanInterval": n => { windows10GeneralConfiguration.wiFiScanInterval = n.getNumberValue() as any ; },
        "windowsSpotlightBlockConsumerSpecificFeatures": n => { windows10GeneralConfiguration.windowsSpotlightBlockConsumerSpecificFeatures = n.getBooleanValue() as any ; },
        "windowsSpotlightBlocked": n => { windows10GeneralConfiguration.windowsSpotlightBlocked = n.getBooleanValue() as any ; },
        "windowsSpotlightBlockOnActionCenter": n => { windows10GeneralConfiguration.windowsSpotlightBlockOnActionCenter = n.getBooleanValue() as any ; },
        "windowsSpotlightBlockTailoredExperiences": n => { windows10GeneralConfiguration.windowsSpotlightBlockTailoredExperiences = n.getBooleanValue() as any ; },
        "windowsSpotlightBlockThirdPartyNotifications": n => { windows10GeneralConfiguration.windowsSpotlightBlockThirdPartyNotifications = n.getBooleanValue() as any ; },
        "windowsSpotlightBlockWelcomeExperience": n => { windows10GeneralConfiguration.windowsSpotlightBlockWelcomeExperience = n.getBooleanValue() as any ; },
        "windowsSpotlightBlockWindowsTips": n => { windows10GeneralConfiguration.windowsSpotlightBlockWindowsTips = n.getBooleanValue() as any ; },
        "windowsSpotlightConfigureOnLockScreen": n => { windows10GeneralConfiguration.windowsSpotlightConfigureOnLockScreen = n.getEnumValue<WindowsSpotlightEnablementSettings>(WindowsSpotlightEnablementSettings) as any ; },
        "windowsStoreBlockAutoUpdate": n => { windows10GeneralConfiguration.windowsStoreBlockAutoUpdate = n.getBooleanValue() as any ; },
        "windowsStoreBlocked": n => { windows10GeneralConfiguration.windowsStoreBlocked = n.getBooleanValue() as any ; },
        "windowsStoreEnablePrivateStoreOnly": n => { windows10GeneralConfiguration.windowsStoreEnablePrivateStoreOnly = n.getBooleanValue() as any ; },
        "wirelessDisplayBlockProjectionToThisDevice": n => { windows10GeneralConfiguration.wirelessDisplayBlockProjectionToThisDevice = n.getBooleanValue() as any ; },
        "wirelessDisplayBlockUserInputFromReceiver": n => { windows10GeneralConfiguration.wirelessDisplayBlockUserInputFromReceiver = n.getBooleanValue() as any ; },
        "wirelessDisplayRequirePinForPairing": n => { windows10GeneralConfiguration.wirelessDisplayRequirePinForPairing = n.getBooleanValue() as any ; },
    }
}
