import {AppListType} from './appListType';
import {deserializeIntoAppListItem} from './deserializeIntoAppListItem';
import {deserializeIntoDeviceConfiguration} from './deserializeIntoDeviceConfiguration';
import {deserializeIntoIosNetworkUsageRule} from './deserializeIntoIosNetworkUsageRule';
import {deserializeIntoMediaContentRatingAustralia} from './deserializeIntoMediaContentRatingAustralia';
import {deserializeIntoMediaContentRatingCanada} from './deserializeIntoMediaContentRatingCanada';
import {deserializeIntoMediaContentRatingFrance} from './deserializeIntoMediaContentRatingFrance';
import {deserializeIntoMediaContentRatingGermany} from './deserializeIntoMediaContentRatingGermany';
import {deserializeIntoMediaContentRatingIreland} from './deserializeIntoMediaContentRatingIreland';
import {deserializeIntoMediaContentRatingJapan} from './deserializeIntoMediaContentRatingJapan';
import {deserializeIntoMediaContentRatingNewZealand} from './deserializeIntoMediaContentRatingNewZealand';
import {deserializeIntoMediaContentRatingUnitedKingdom} from './deserializeIntoMediaContentRatingUnitedKingdom';
import {deserializeIntoMediaContentRatingUnitedStates} from './deserializeIntoMediaContentRatingUnitedStates';
import {IosGeneralDeviceConfiguration} from './index';
import {RatingAppsType} from './ratingAppsType';
import {RequiredPasswordType} from './requiredPasswordType';
import {WebBrowserCookieSettings} from './webBrowserCookieSettings';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function deserializeIntoIosGeneralDeviceConfiguration(iosGeneralDeviceConfiguration: IosGeneralDeviceConfiguration | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoDeviceConfiguration(iosGeneralDeviceConfiguration),
        "accountBlockModification": n => { iosGeneralDeviceConfiguration.accountBlockModification = n.getBooleanValue() as any ; },
        "activationLockAllowWhenSupervised": n => { iosGeneralDeviceConfiguration.activationLockAllowWhenSupervised = n.getBooleanValue() as any ; },
        "airDropBlocked": n => { iosGeneralDeviceConfiguration.airDropBlocked = n.getBooleanValue() as any ; },
        "airDropForceUnmanagedDropTarget": n => { iosGeneralDeviceConfiguration.airDropForceUnmanagedDropTarget = n.getBooleanValue() as any ; },
        "airPlayForcePairingPasswordForOutgoingRequests": n => { iosGeneralDeviceConfiguration.airPlayForcePairingPasswordForOutgoingRequests = n.getBooleanValue() as any ; },
        "appleNewsBlocked": n => { iosGeneralDeviceConfiguration.appleNewsBlocked = n.getBooleanValue() as any ; },
        "appleWatchBlockPairing": n => { iosGeneralDeviceConfiguration.appleWatchBlockPairing = n.getBooleanValue() as any ; },
        "appleWatchForceWristDetection": n => { iosGeneralDeviceConfiguration.appleWatchForceWristDetection = n.getBooleanValue() as any ; },
        "appsSingleAppModeList": n => { iosGeneralDeviceConfiguration.appsSingleAppModeList = n.getCollectionOfObjectValuesFromMethod(deserializeIntoAppListItem) as any ; },
        "appStoreBlockAutomaticDownloads": n => { iosGeneralDeviceConfiguration.appStoreBlockAutomaticDownloads = n.getBooleanValue() as any ; },
        "appStoreBlocked": n => { iosGeneralDeviceConfiguration.appStoreBlocked = n.getBooleanValue() as any ; },
        "appStoreBlockInAppPurchases": n => { iosGeneralDeviceConfiguration.appStoreBlockInAppPurchases = n.getBooleanValue() as any ; },
        "appStoreBlockUIAppInstallation": n => { iosGeneralDeviceConfiguration.appStoreBlockUIAppInstallation = n.getBooleanValue() as any ; },
        "appStoreRequirePassword": n => { iosGeneralDeviceConfiguration.appStoreRequirePassword = n.getBooleanValue() as any ; },
        "appsVisibilityList": n => { iosGeneralDeviceConfiguration.appsVisibilityList = n.getCollectionOfObjectValuesFromMethod(deserializeIntoAppListItem) as any ; },
        "appsVisibilityListType": n => { iosGeneralDeviceConfiguration.appsVisibilityListType = n.getEnumValue<AppListType>(AppListType) as any ; },
        "bluetoothBlockModification": n => { iosGeneralDeviceConfiguration.bluetoothBlockModification = n.getBooleanValue() as any ; },
        "cameraBlocked": n => { iosGeneralDeviceConfiguration.cameraBlocked = n.getBooleanValue() as any ; },
        "cellularBlockDataRoaming": n => { iosGeneralDeviceConfiguration.cellularBlockDataRoaming = n.getBooleanValue() as any ; },
        "cellularBlockGlobalBackgroundFetchWhileRoaming": n => { iosGeneralDeviceConfiguration.cellularBlockGlobalBackgroundFetchWhileRoaming = n.getBooleanValue() as any ; },
        "cellularBlockPerAppDataModification": n => { iosGeneralDeviceConfiguration.cellularBlockPerAppDataModification = n.getBooleanValue() as any ; },
        "cellularBlockPersonalHotspot": n => { iosGeneralDeviceConfiguration.cellularBlockPersonalHotspot = n.getBooleanValue() as any ; },
        "cellularBlockVoiceRoaming": n => { iosGeneralDeviceConfiguration.cellularBlockVoiceRoaming = n.getBooleanValue() as any ; },
        "certificatesBlockUntrustedTlsCertificates": n => { iosGeneralDeviceConfiguration.certificatesBlockUntrustedTlsCertificates = n.getBooleanValue() as any ; },
        "classroomAppBlockRemoteScreenObservation": n => { iosGeneralDeviceConfiguration.classroomAppBlockRemoteScreenObservation = n.getBooleanValue() as any ; },
        "classroomAppForceUnpromptedScreenObservation": n => { iosGeneralDeviceConfiguration.classroomAppForceUnpromptedScreenObservation = n.getBooleanValue() as any ; },
        "compliantAppListType": n => { iosGeneralDeviceConfiguration.compliantAppListType = n.getEnumValue<AppListType>(AppListType) as any ; },
        "compliantAppsList": n => { iosGeneralDeviceConfiguration.compliantAppsList = n.getCollectionOfObjectValuesFromMethod(deserializeIntoAppListItem) as any ; },
        "configurationProfileBlockChanges": n => { iosGeneralDeviceConfiguration.configurationProfileBlockChanges = n.getBooleanValue() as any ; },
        "definitionLookupBlocked": n => { iosGeneralDeviceConfiguration.definitionLookupBlocked = n.getBooleanValue() as any ; },
        "deviceBlockEnableRestrictions": n => { iosGeneralDeviceConfiguration.deviceBlockEnableRestrictions = n.getBooleanValue() as any ; },
        "deviceBlockEraseContentAndSettings": n => { iosGeneralDeviceConfiguration.deviceBlockEraseContentAndSettings = n.getBooleanValue() as any ; },
        "deviceBlockNameModification": n => { iosGeneralDeviceConfiguration.deviceBlockNameModification = n.getBooleanValue() as any ; },
        "diagnosticDataBlockSubmission": n => { iosGeneralDeviceConfiguration.diagnosticDataBlockSubmission = n.getBooleanValue() as any ; },
        "diagnosticDataBlockSubmissionModification": n => { iosGeneralDeviceConfiguration.diagnosticDataBlockSubmissionModification = n.getBooleanValue() as any ; },
        "documentsBlockManagedDocumentsInUnmanagedApps": n => { iosGeneralDeviceConfiguration.documentsBlockManagedDocumentsInUnmanagedApps = n.getBooleanValue() as any ; },
        "documentsBlockUnmanagedDocumentsInManagedApps": n => { iosGeneralDeviceConfiguration.documentsBlockUnmanagedDocumentsInManagedApps = n.getBooleanValue() as any ; },
        "emailInDomainSuffixes": n => { iosGeneralDeviceConfiguration.emailInDomainSuffixes = n.getCollectionOfPrimitiveValues<string>() as any ; },
        "enterpriseAppBlockTrust": n => { iosGeneralDeviceConfiguration.enterpriseAppBlockTrust = n.getBooleanValue() as any ; },
        "enterpriseAppBlockTrustModification": n => { iosGeneralDeviceConfiguration.enterpriseAppBlockTrustModification = n.getBooleanValue() as any ; },
        "faceTimeBlocked": n => { iosGeneralDeviceConfiguration.faceTimeBlocked = n.getBooleanValue() as any ; },
        "findMyFriendsBlocked": n => { iosGeneralDeviceConfiguration.findMyFriendsBlocked = n.getBooleanValue() as any ; },
        "gameCenterBlocked": n => { iosGeneralDeviceConfiguration.gameCenterBlocked = n.getBooleanValue() as any ; },
        "gamingBlockGameCenterFriends": n => { iosGeneralDeviceConfiguration.gamingBlockGameCenterFriends = n.getBooleanValue() as any ; },
        "gamingBlockMultiplayer": n => { iosGeneralDeviceConfiguration.gamingBlockMultiplayer = n.getBooleanValue() as any ; },
        "hostPairingBlocked": n => { iosGeneralDeviceConfiguration.hostPairingBlocked = n.getBooleanValue() as any ; },
        "iBooksStoreBlocked": n => { iosGeneralDeviceConfiguration.iBooksStoreBlocked = n.getBooleanValue() as any ; },
        "iBooksStoreBlockErotica": n => { iosGeneralDeviceConfiguration.iBooksStoreBlockErotica = n.getBooleanValue() as any ; },
        "iCloudBlockActivityContinuation": n => { iosGeneralDeviceConfiguration.iCloudBlockActivityContinuation = n.getBooleanValue() as any ; },
        "iCloudBlockBackup": n => { iosGeneralDeviceConfiguration.iCloudBlockBackup = n.getBooleanValue() as any ; },
        "iCloudBlockDocumentSync": n => { iosGeneralDeviceConfiguration.iCloudBlockDocumentSync = n.getBooleanValue() as any ; },
        "iCloudBlockManagedAppsSync": n => { iosGeneralDeviceConfiguration.iCloudBlockManagedAppsSync = n.getBooleanValue() as any ; },
        "iCloudBlockPhotoLibrary": n => { iosGeneralDeviceConfiguration.iCloudBlockPhotoLibrary = n.getBooleanValue() as any ; },
        "iCloudBlockPhotoStreamSync": n => { iosGeneralDeviceConfiguration.iCloudBlockPhotoStreamSync = n.getBooleanValue() as any ; },
        "iCloudBlockSharedPhotoStream": n => { iosGeneralDeviceConfiguration.iCloudBlockSharedPhotoStream = n.getBooleanValue() as any ; },
        "iCloudRequireEncryptedBackup": n => { iosGeneralDeviceConfiguration.iCloudRequireEncryptedBackup = n.getBooleanValue() as any ; },
        "iTunesBlockExplicitContent": n => { iosGeneralDeviceConfiguration.iTunesBlockExplicitContent = n.getBooleanValue() as any ; },
        "iTunesBlockMusicService": n => { iosGeneralDeviceConfiguration.iTunesBlockMusicService = n.getBooleanValue() as any ; },
        "iTunesBlockRadio": n => { iosGeneralDeviceConfiguration.iTunesBlockRadio = n.getBooleanValue() as any ; },
        "keyboardBlockAutoCorrect": n => { iosGeneralDeviceConfiguration.keyboardBlockAutoCorrect = n.getBooleanValue() as any ; },
        "keyboardBlockDictation": n => { iosGeneralDeviceConfiguration.keyboardBlockDictation = n.getBooleanValue() as any ; },
        "keyboardBlockPredictive": n => { iosGeneralDeviceConfiguration.keyboardBlockPredictive = n.getBooleanValue() as any ; },
        "keyboardBlockShortcuts": n => { iosGeneralDeviceConfiguration.keyboardBlockShortcuts = n.getBooleanValue() as any ; },
        "keyboardBlockSpellCheck": n => { iosGeneralDeviceConfiguration.keyboardBlockSpellCheck = n.getBooleanValue() as any ; },
        "kioskModeAllowAssistiveSpeak": n => { iosGeneralDeviceConfiguration.kioskModeAllowAssistiveSpeak = n.getBooleanValue() as any ; },
        "kioskModeAllowAssistiveTouchSettings": n => { iosGeneralDeviceConfiguration.kioskModeAllowAssistiveTouchSettings = n.getBooleanValue() as any ; },
        "kioskModeAllowAutoLock": n => { iosGeneralDeviceConfiguration.kioskModeAllowAutoLock = n.getBooleanValue() as any ; },
        "kioskModeAllowColorInversionSettings": n => { iosGeneralDeviceConfiguration.kioskModeAllowColorInversionSettings = n.getBooleanValue() as any ; },
        "kioskModeAllowRingerSwitch": n => { iosGeneralDeviceConfiguration.kioskModeAllowRingerSwitch = n.getBooleanValue() as any ; },
        "kioskModeAllowScreenRotation": n => { iosGeneralDeviceConfiguration.kioskModeAllowScreenRotation = n.getBooleanValue() as any ; },
        "kioskModeAllowSleepButton": n => { iosGeneralDeviceConfiguration.kioskModeAllowSleepButton = n.getBooleanValue() as any ; },
        "kioskModeAllowTouchscreen": n => { iosGeneralDeviceConfiguration.kioskModeAllowTouchscreen = n.getBooleanValue() as any ; },
        "kioskModeAllowVoiceOverSettings": n => { iosGeneralDeviceConfiguration.kioskModeAllowVoiceOverSettings = n.getBooleanValue() as any ; },
        "kioskModeAllowVolumeButtons": n => { iosGeneralDeviceConfiguration.kioskModeAllowVolumeButtons = n.getBooleanValue() as any ; },
        "kioskModeAllowZoomSettings": n => { iosGeneralDeviceConfiguration.kioskModeAllowZoomSettings = n.getBooleanValue() as any ; },
        "kioskModeAppStoreUrl": n => { iosGeneralDeviceConfiguration.kioskModeAppStoreUrl = n.getStringValue() as any ; },
        "kioskModeBuiltInAppId": n => { iosGeneralDeviceConfiguration.kioskModeBuiltInAppId = n.getStringValue() as any ; },
        "kioskModeManagedAppId": n => { iosGeneralDeviceConfiguration.kioskModeManagedAppId = n.getStringValue() as any ; },
        "kioskModeRequireAssistiveTouch": n => { iosGeneralDeviceConfiguration.kioskModeRequireAssistiveTouch = n.getBooleanValue() as any ; },
        "kioskModeRequireColorInversion": n => { iosGeneralDeviceConfiguration.kioskModeRequireColorInversion = n.getBooleanValue() as any ; },
        "kioskModeRequireMonoAudio": n => { iosGeneralDeviceConfiguration.kioskModeRequireMonoAudio = n.getBooleanValue() as any ; },
        "kioskModeRequireVoiceOver": n => { iosGeneralDeviceConfiguration.kioskModeRequireVoiceOver = n.getBooleanValue() as any ; },
        "kioskModeRequireZoom": n => { iosGeneralDeviceConfiguration.kioskModeRequireZoom = n.getBooleanValue() as any ; },
        "lockScreenBlockControlCenter": n => { iosGeneralDeviceConfiguration.lockScreenBlockControlCenter = n.getBooleanValue() as any ; },
        "lockScreenBlockNotificationView": n => { iosGeneralDeviceConfiguration.lockScreenBlockNotificationView = n.getBooleanValue() as any ; },
        "lockScreenBlockPassbook": n => { iosGeneralDeviceConfiguration.lockScreenBlockPassbook = n.getBooleanValue() as any ; },
        "lockScreenBlockTodayView": n => { iosGeneralDeviceConfiguration.lockScreenBlockTodayView = n.getBooleanValue() as any ; },
        "mediaContentRatingApps": n => { iosGeneralDeviceConfiguration.mediaContentRatingApps = n.getEnumValue<RatingAppsType>(RatingAppsType) as any ; },
        "mediaContentRatingAustralia": n => { iosGeneralDeviceConfiguration.mediaContentRatingAustralia = n.getObject(deserializeIntoMediaContentRatingAustralia) as any ; },
        "mediaContentRatingCanada": n => { iosGeneralDeviceConfiguration.mediaContentRatingCanada = n.getObject(deserializeIntoMediaContentRatingCanada) as any ; },
        "mediaContentRatingFrance": n => { iosGeneralDeviceConfiguration.mediaContentRatingFrance = n.getObject(deserializeIntoMediaContentRatingFrance) as any ; },
        "mediaContentRatingGermany": n => { iosGeneralDeviceConfiguration.mediaContentRatingGermany = n.getObject(deserializeIntoMediaContentRatingGermany) as any ; },
        "mediaContentRatingIreland": n => { iosGeneralDeviceConfiguration.mediaContentRatingIreland = n.getObject(deserializeIntoMediaContentRatingIreland) as any ; },
        "mediaContentRatingJapan": n => { iosGeneralDeviceConfiguration.mediaContentRatingJapan = n.getObject(deserializeIntoMediaContentRatingJapan) as any ; },
        "mediaContentRatingNewZealand": n => { iosGeneralDeviceConfiguration.mediaContentRatingNewZealand = n.getObject(deserializeIntoMediaContentRatingNewZealand) as any ; },
        "mediaContentRatingUnitedKingdom": n => { iosGeneralDeviceConfiguration.mediaContentRatingUnitedKingdom = n.getObject(deserializeIntoMediaContentRatingUnitedKingdom) as any ; },
        "mediaContentRatingUnitedStates": n => { iosGeneralDeviceConfiguration.mediaContentRatingUnitedStates = n.getObject(deserializeIntoMediaContentRatingUnitedStates) as any ; },
        "messagesBlocked": n => { iosGeneralDeviceConfiguration.messagesBlocked = n.getBooleanValue() as any ; },
        "networkUsageRules": n => { iosGeneralDeviceConfiguration.networkUsageRules = n.getCollectionOfObjectValuesFromMethod(deserializeIntoIosNetworkUsageRule) as any ; },
        "notificationsBlockSettingsModification": n => { iosGeneralDeviceConfiguration.notificationsBlockSettingsModification = n.getBooleanValue() as any ; },
        "passcodeBlockFingerprintModification": n => { iosGeneralDeviceConfiguration.passcodeBlockFingerprintModification = n.getBooleanValue() as any ; },
        "passcodeBlockFingerprintUnlock": n => { iosGeneralDeviceConfiguration.passcodeBlockFingerprintUnlock = n.getBooleanValue() as any ; },
        "passcodeBlockModification": n => { iosGeneralDeviceConfiguration.passcodeBlockModification = n.getBooleanValue() as any ; },
        "passcodeBlockSimple": n => { iosGeneralDeviceConfiguration.passcodeBlockSimple = n.getBooleanValue() as any ; },
        "passcodeExpirationDays": n => { iosGeneralDeviceConfiguration.passcodeExpirationDays = n.getNumberValue() as any ; },
        "passcodeMinimumCharacterSetCount": n => { iosGeneralDeviceConfiguration.passcodeMinimumCharacterSetCount = n.getNumberValue() as any ; },
        "passcodeMinimumLength": n => { iosGeneralDeviceConfiguration.passcodeMinimumLength = n.getNumberValue() as any ; },
        "passcodeMinutesOfInactivityBeforeLock": n => { iosGeneralDeviceConfiguration.passcodeMinutesOfInactivityBeforeLock = n.getNumberValue() as any ; },
        "passcodeMinutesOfInactivityBeforeScreenTimeout": n => { iosGeneralDeviceConfiguration.passcodeMinutesOfInactivityBeforeScreenTimeout = n.getNumberValue() as any ; },
        "passcodePreviousPasscodeBlockCount": n => { iosGeneralDeviceConfiguration.passcodePreviousPasscodeBlockCount = n.getNumberValue() as any ; },
        "passcodeRequired": n => { iosGeneralDeviceConfiguration.passcodeRequired = n.getBooleanValue() as any ; },
        "passcodeRequiredType": n => { iosGeneralDeviceConfiguration.passcodeRequiredType = n.getEnumValue<RequiredPasswordType>(RequiredPasswordType) as any ; },
        "passcodeSignInFailureCountBeforeWipe": n => { iosGeneralDeviceConfiguration.passcodeSignInFailureCountBeforeWipe = n.getNumberValue() as any ; },
        "podcastsBlocked": n => { iosGeneralDeviceConfiguration.podcastsBlocked = n.getBooleanValue() as any ; },
        "safariBlockAutofill": n => { iosGeneralDeviceConfiguration.safariBlockAutofill = n.getBooleanValue() as any ; },
        "safariBlocked": n => { iosGeneralDeviceConfiguration.safariBlocked = n.getBooleanValue() as any ; },
        "safariBlockJavaScript": n => { iosGeneralDeviceConfiguration.safariBlockJavaScript = n.getBooleanValue() as any ; },
        "safariBlockPopups": n => { iosGeneralDeviceConfiguration.safariBlockPopups = n.getBooleanValue() as any ; },
        "safariCookieSettings": n => { iosGeneralDeviceConfiguration.safariCookieSettings = n.getEnumValue<WebBrowserCookieSettings>(WebBrowserCookieSettings) as any ; },
        "safariManagedDomains": n => { iosGeneralDeviceConfiguration.safariManagedDomains = n.getCollectionOfPrimitiveValues<string>() as any ; },
        "safariPasswordAutoFillDomains": n => { iosGeneralDeviceConfiguration.safariPasswordAutoFillDomains = n.getCollectionOfPrimitiveValues<string>() as any ; },
        "safariRequireFraudWarning": n => { iosGeneralDeviceConfiguration.safariRequireFraudWarning = n.getBooleanValue() as any ; },
        "screenCaptureBlocked": n => { iosGeneralDeviceConfiguration.screenCaptureBlocked = n.getBooleanValue() as any ; },
        "siriBlocked": n => { iosGeneralDeviceConfiguration.siriBlocked = n.getBooleanValue() as any ; },
        "siriBlockedWhenLocked": n => { iosGeneralDeviceConfiguration.siriBlockedWhenLocked = n.getBooleanValue() as any ; },
        "siriBlockUserGeneratedContent": n => { iosGeneralDeviceConfiguration.siriBlockUserGeneratedContent = n.getBooleanValue() as any ; },
        "siriRequireProfanityFilter": n => { iosGeneralDeviceConfiguration.siriRequireProfanityFilter = n.getBooleanValue() as any ; },
        "spotlightBlockInternetResults": n => { iosGeneralDeviceConfiguration.spotlightBlockInternetResults = n.getBooleanValue() as any ; },
        "voiceDialingBlocked": n => { iosGeneralDeviceConfiguration.voiceDialingBlocked = n.getBooleanValue() as any ; },
        "wallpaperBlockModification": n => { iosGeneralDeviceConfiguration.wallpaperBlockModification = n.getBooleanValue() as any ; },
        "wiFiConnectOnlyToConfiguredNetworks": n => { iosGeneralDeviceConfiguration.wiFiConnectOnlyToConfiguredNetworks = n.getBooleanValue() as any ; },
    }
}
