import {DriveItem} from './index';
import {serializeAudio} from './serializeAudio';
import {serializeBaseItem} from './serializeBaseItem';
import {serializeBundle} from './serializeBundle';
import {serializeDeleted} from './serializeDeleted';
import {serializeDriveItemSource} from './serializeDriveItemSource';
import {serializeDriveItemVersion} from './serializeDriveItemVersion';
import {serializeFile} from './serializeFile';
import {serializeFileSystemInfo} from './serializeFileSystemInfo';
import {serializeFolder} from './serializeFolder';
import {serializeGeoCoordinates} from './serializeGeoCoordinates';
import {serializeImage} from './serializeImage';
import {serializeItemActivityOLD} from './serializeItemActivityOLD';
import {serializeItemAnalytics} from './serializeItemAnalytics';
import {serializeListItem} from './serializeListItem';
import {serializeMalware} from './serializeMalware';
import {serializeMedia} from './serializeMedia';
import {serializePackage} from './serializePackage';
import {serializePendingOperations} from './serializePendingOperations';
import {serializePermission} from './serializePermission';
import {serializePhoto} from './serializePhoto';
import {serializePublicationFacet} from './serializePublicationFacet';
import {serializeRemoteItem} from './serializeRemoteItem';
import {serializeRoot} from './serializeRoot';
import {serializeSearchResult} from './serializeSearchResult';
import {serializeShared} from './serializeShared';
import {serializeSharepointIds} from './serializeSharepointIds';
import {serializeSpecialFolder} from './serializeSpecialFolder';
import {serializeSubscription} from './serializeSubscription';
import {serializeThumbnailSet} from './serializeThumbnailSet';
import {serializeVideo} from './serializeVideo';
import {serializeWorkbook} from './serializeWorkbook';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeDriveItem(writer: SerializationWriter, driveItem: DriveItem | undefined = {}) : void {
        serializeBaseItem(writer, driveItem)
            writer.writeCollectionOfObjectValuesFromMethod("activities", driveItem.activities as any, serializeItemActivityOLD);
            writer.writeObjectValueFromMethod("analytics", driveItem.analytics as any, serializeItemAnalytics);
            writer.writeObjectValueFromMethod("audio", driveItem.audio as any, serializeAudio);
            writer.writeObjectValueFromMethod("bundle", driveItem.bundle as any, serializeBundle);
            writer.writeCollectionOfObjectValuesFromMethod("children", driveItem.children as any, serializeDriveItem);
            writer.writeStringValue("content", driveItem.content);
            writer.writeStringValue("cTag", driveItem.cTag);
            writer.writeObjectValueFromMethod("deleted", driveItem.deleted as any, serializeDeleted);
            writer.writeObjectValueFromMethod("file", driveItem.file as any, serializeFile);
            writer.writeObjectValueFromMethod("fileSystemInfo", driveItem.fileSystemInfo as any, serializeFileSystemInfo);
            writer.writeObjectValueFromMethod("folder", driveItem.folder as any, serializeFolder);
            writer.writeObjectValueFromMethod("image", driveItem.image as any, serializeImage);
            writer.writeObjectValueFromMethod("listItem", driveItem.listItem as any, serializeListItem);
            writer.writeObjectValueFromMethod("location", driveItem.location as any, serializeGeoCoordinates);
            writer.writeObjectValueFromMethod("malware", driveItem.malware as any, serializeMalware);
            writer.writeObjectValueFromMethod("media", driveItem.media as any, serializeMedia);
            writer.writeObjectValueFromMethod("package", driveItem.package as any, serializePackage);
            writer.writeObjectValueFromMethod("pendingOperations", driveItem.pendingOperations as any, serializePendingOperations);
            writer.writeCollectionOfObjectValuesFromMethod("permissions", driveItem.permissions as any, serializePermission);
            writer.writeObjectValueFromMethod("photo", driveItem.photo as any, serializePhoto);
            writer.writeObjectValueFromMethod("publication", driveItem.publication as any, serializePublicationFacet);
            writer.writeObjectValueFromMethod("remoteItem", driveItem.remoteItem as any, serializeRemoteItem);
            writer.writeObjectValueFromMethod("root", driveItem.root as any, serializeRoot);
            writer.writeObjectValueFromMethod("searchResult", driveItem.searchResult as any, serializeSearchResult);
            writer.writeObjectValueFromMethod("shared", driveItem.shared as any, serializeShared);
            writer.writeObjectValueFromMethod("sharepointIds", driveItem.sharepointIds as any, serializeSharepointIds);
            writer.writeNumberValue("size", driveItem.size);
            writer.writeObjectValueFromMethod("source", driveItem.source as any, serializeDriveItemSource);
            writer.writeObjectValueFromMethod("specialFolder", driveItem.specialFolder as any, serializeSpecialFolder);
            writer.writeCollectionOfObjectValuesFromMethod("subscriptions", driveItem.subscriptions as any, serializeSubscription);
            writer.writeCollectionOfObjectValuesFromMethod("thumbnails", driveItem.thumbnails as any, serializeThumbnailSet);
            writer.writeCollectionOfObjectValuesFromMethod("versions", driveItem.versions as any, serializeDriveItemVersion);
            writer.writeObjectValueFromMethod("video", driveItem.video as any, serializeVideo);
            writer.writeStringValue("webDavUrl", driveItem.webDavUrl);
            writer.writeObjectValueFromMethod("workbook", driveItem.workbook as any, serializeWorkbook);
}
