import {User} from './index';
import {serializeAgreementAcceptance} from './serializeAgreementAcceptance';
import {serializeAppRoleAssignment} from './serializeAppRoleAssignment';
import {serializeAssignedLicense} from './serializeAssignedLicense';
import {serializeAssignedPlan} from './serializeAssignedPlan';
import {serializeAuthentication} from './serializeAuthentication';
import {serializeAuthorizationInfo} from './serializeAuthorizationInfo';
import {serializeCalendar} from './serializeCalendar';
import {serializeCalendarGroup} from './serializeCalendarGroup';
import {serializeChat} from './serializeChat';
import {serializeContact} from './serializeContact';
import {serializeContactFolder} from './serializeContactFolder';
import {serializeDeviceManagementTroubleshootingEvent} from './serializeDeviceManagementTroubleshootingEvent';
import {serializeDirectoryObject} from './serializeDirectoryObject';
import {serializeDrive} from './serializeDrive';
import {serializeEmployeeOrgData} from './serializeEmployeeOrgData';
import {serializeEvent} from './serializeEvent';
import {serializeExtension} from './serializeExtension';
import {serializeInferenceClassification} from './serializeInferenceClassification';
import {serializeLicenseAssignmentState} from './serializeLicenseAssignmentState';
import {serializeLicenseDetails} from './serializeLicenseDetails';
import {serializeMailboxSettings} from './serializeMailboxSettings';
import {serializeMailFolder} from './serializeMailFolder';
import {serializeManagedAppRegistration} from './serializeManagedAppRegistration';
import {serializeManagedDevice} from './serializeManagedDevice';
import {serializeMessage} from './serializeMessage';
import {serializeOAuth2PermissionGrant} from './serializeOAuth2PermissionGrant';
import {serializeObjectIdentity} from './serializeObjectIdentity';
import {serializeOfficeGraphInsights} from './serializeOfficeGraphInsights';
import {serializeOnenote} from './serializeOnenote';
import {serializeOnlineMeeting} from './serializeOnlineMeeting';
import {serializeOnPremisesExtensionAttributes} from './serializeOnPremisesExtensionAttributes';
import {serializeOnPremisesProvisioningError} from './serializeOnPremisesProvisioningError';
import {serializeOutlookUser} from './serializeOutlookUser';
import {serializePasswordProfile} from './serializePasswordProfile';
import {serializePerson} from './serializePerson';
import {serializePlannerUser} from './serializePlannerUser';
import {serializePresence} from './serializePresence';
import {serializeProfilePhoto} from './serializeProfilePhoto';
import {serializeProvisionedPlan} from './serializeProvisionedPlan';
import {serializeScopedRoleMembership} from './serializeScopedRoleMembership';
import {serializeSite} from './serializeSite';
import {serializeTeam} from './serializeTeam';
import {serializeTodo} from './serializeTodo';
import {serializeUserActivity} from './serializeUserActivity';
import {serializeUserSettings} from './serializeUserSettings';
import {serializeUserTeamwork} from './serializeUserTeamwork';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeUser(writer: SerializationWriter, user: User | undefined = {}) : void {
        serializeDirectoryObject(writer, user)
            writer.writeStringValue("aboutMe", user.aboutMe);
            writer.writeBooleanValue("accountEnabled", user.accountEnabled);
            writer.writeCollectionOfObjectValuesFromMethod("activities", user.activities as any, serializeUserActivity);
            writer.writeStringValue("ageGroup", user.ageGroup);
            writer.writeCollectionOfObjectValuesFromMethod("agreementAcceptances", user.agreementAcceptances as any, serializeAgreementAcceptance);
            writer.writeCollectionOfObjectValuesFromMethod("appRoleAssignments", user.appRoleAssignments as any, serializeAppRoleAssignment);
            writer.writeCollectionOfObjectValuesFromMethod("assignedLicenses", user.assignedLicenses as any, serializeAssignedLicense);
            writer.writeCollectionOfObjectValuesFromMethod("assignedPlans", user.assignedPlans as any, serializeAssignedPlan);
            writer.writeObjectValueFromMethod("authentication", user.authentication as any, serializeAuthentication);
            writer.writeObjectValueFromMethod("authorizationInfo", user.authorizationInfo as any, serializeAuthorizationInfo);
            writer.writeDateValue("birthday", user.birthday);
            writer.writeCollectionOfPrimitiveValues<string>("businessPhones", user.businessPhones);
            writer.writeObjectValueFromMethod("calendar", user.calendar as any, serializeCalendar);
            writer.writeCollectionOfObjectValuesFromMethod("calendarGroups", user.calendarGroups as any, serializeCalendarGroup);
            writer.writeCollectionOfObjectValuesFromMethod("calendars", user.calendars as any, serializeCalendar);
            writer.writeCollectionOfObjectValuesFromMethod("calendarView", user.calendarView as any, serializeEvent);
            writer.writeCollectionOfObjectValuesFromMethod("chats", user.chats as any, serializeChat);
            writer.writeStringValue("city", user.city);
            writer.writeStringValue("companyName", user.companyName);
            writer.writeStringValue("consentProvidedForMinor", user.consentProvidedForMinor);
            writer.writeCollectionOfObjectValuesFromMethod("contactFolders", user.contactFolders as any, serializeContactFolder);
            writer.writeCollectionOfObjectValuesFromMethod("contacts", user.contacts as any, serializeContact);
            writer.writeStringValue("country", user.country);
            writer.writeDateValue("createdDateTime", user.createdDateTime);
            writer.writeCollectionOfObjectValuesFromMethod("createdObjects", user.createdObjects as any, serializeDirectoryObject);
            writer.writeStringValue("creationType", user.creationType);
            writer.writeStringValue("department", user.department);
            writer.writeNumberValue("deviceEnrollmentLimit", user.deviceEnrollmentLimit);
            writer.writeCollectionOfObjectValuesFromMethod("deviceManagementTroubleshootingEvents", user.deviceManagementTroubleshootingEvents as any, serializeDeviceManagementTroubleshootingEvent);
            writer.writeCollectionOfObjectValuesFromMethod("directReports", user.directReports as any, serializeDirectoryObject);
            writer.writeStringValue("displayName", user.displayName);
            writer.writeObjectValueFromMethod("drive", user.drive as any, serializeDrive);
            writer.writeCollectionOfObjectValuesFromMethod("drives", user.drives as any, serializeDrive);
            writer.writeDateValue("employeeHireDate", user.employeeHireDate);
            writer.writeStringValue("employeeId", user.employeeId);
            writer.writeObjectValueFromMethod("employeeOrgData", user.employeeOrgData as any, serializeEmployeeOrgData);
            writer.writeStringValue("employeeType", user.employeeType);
            writer.writeCollectionOfObjectValuesFromMethod("events", user.events as any, serializeEvent);
            writer.writeCollectionOfObjectValuesFromMethod("extensions", user.extensions as any, serializeExtension);
            writer.writeStringValue("externalUserState", user.externalUserState);
            writer.writeDateValue("externalUserStateChangeDateTime", user.externalUserStateChangeDateTime);
            writer.writeStringValue("faxNumber", user.faxNumber);
            writer.writeCollectionOfObjectValuesFromMethod("followedSites", user.followedSites as any, serializeSite);
            writer.writeStringValue("givenName", user.givenName);
            writer.writeDateValue("hireDate", user.hireDate);
            writer.writeCollectionOfObjectValuesFromMethod("identities", user.identities as any, serializeObjectIdentity);
            writer.writeCollectionOfPrimitiveValues<string>("imAddresses", user.imAddresses);
            writer.writeObjectValueFromMethod("inferenceClassification", user.inferenceClassification as any, serializeInferenceClassification);
            writer.writeObjectValueFromMethod("insights", user.insights as any, serializeOfficeGraphInsights);
            writer.writeCollectionOfPrimitiveValues<string>("interests", user.interests);
            writer.writeBooleanValue("isResourceAccount", user.isResourceAccount);
            writer.writeStringValue("jobTitle", user.jobTitle);
            writer.writeCollectionOfObjectValuesFromMethod("joinedTeams", user.joinedTeams as any, serializeTeam);
            writer.writeDateValue("lastPasswordChangeDateTime", user.lastPasswordChangeDateTime);
            writer.writeStringValue("legalAgeGroupClassification", user.legalAgeGroupClassification);
            writer.writeCollectionOfObjectValuesFromMethod("licenseAssignmentStates", user.licenseAssignmentStates as any, serializeLicenseAssignmentState);
            writer.writeCollectionOfObjectValuesFromMethod("licenseDetails", user.licenseDetails as any, serializeLicenseDetails);
            writer.writeStringValue("mail", user.mail);
            writer.writeObjectValueFromMethod("mailboxSettings", user.mailboxSettings as any, serializeMailboxSettings);
            writer.writeCollectionOfObjectValuesFromMethod("mailFolders", user.mailFolders as any, serializeMailFolder);
            writer.writeStringValue("mailNickname", user.mailNickname);
            writer.writeCollectionOfObjectValuesFromMethod("managedAppRegistrations", user.managedAppRegistrations as any, serializeManagedAppRegistration);
            writer.writeCollectionOfObjectValuesFromMethod("managedDevices", user.managedDevices as any, serializeManagedDevice);
            writer.writeObjectValueFromMethod("manager", user.manager as any, serializeDirectoryObject);
            writer.writeCollectionOfObjectValuesFromMethod("memberOf", user.memberOf as any, serializeDirectoryObject);
            writer.writeCollectionOfObjectValuesFromMethod("messages", user.messages as any, serializeMessage);
            writer.writeStringValue("mobilePhone", user.mobilePhone);
            writer.writeStringValue("mySite", user.mySite);
            writer.writeCollectionOfObjectValuesFromMethod("oauth2PermissionGrants", user.oauth2PermissionGrants as any, serializeOAuth2PermissionGrant);
            writer.writeStringValue("officeLocation", user.officeLocation);
            writer.writeObjectValueFromMethod("onenote", user.onenote as any, serializeOnenote);
            writer.writeCollectionOfObjectValuesFromMethod("onlineMeetings", user.onlineMeetings as any, serializeOnlineMeeting);
            writer.writeStringValue("onPremisesDistinguishedName", user.onPremisesDistinguishedName);
            writer.writeStringValue("onPremisesDomainName", user.onPremisesDomainName);
            writer.writeObjectValueFromMethod("onPremisesExtensionAttributes", user.onPremisesExtensionAttributes as any, serializeOnPremisesExtensionAttributes);
            writer.writeStringValue("onPremisesImmutableId", user.onPremisesImmutableId);
            writer.writeDateValue("onPremisesLastSyncDateTime", user.onPremisesLastSyncDateTime);
            writer.writeCollectionOfObjectValuesFromMethod("onPremisesProvisioningErrors", user.onPremisesProvisioningErrors as any, serializeOnPremisesProvisioningError);
            writer.writeStringValue("onPremisesSamAccountName", user.onPremisesSamAccountName);
            writer.writeStringValue("onPremisesSecurityIdentifier", user.onPremisesSecurityIdentifier);
            writer.writeBooleanValue("onPremisesSyncEnabled", user.onPremisesSyncEnabled);
            writer.writeStringValue("onPremisesUserPrincipalName", user.onPremisesUserPrincipalName);
            writer.writeCollectionOfPrimitiveValues<string>("otherMails", user.otherMails);
            writer.writeObjectValueFromMethod("outlook", user.outlook as any, serializeOutlookUser);
            writer.writeCollectionOfObjectValuesFromMethod("ownedDevices", user.ownedDevices as any, serializeDirectoryObject);
            writer.writeCollectionOfObjectValuesFromMethod("ownedObjects", user.ownedObjects as any, serializeDirectoryObject);
            writer.writeStringValue("passwordPolicies", user.passwordPolicies);
            writer.writeObjectValueFromMethod("passwordProfile", user.passwordProfile as any, serializePasswordProfile);
            writer.writeCollectionOfPrimitiveValues<string>("pastProjects", user.pastProjects);
            writer.writeCollectionOfObjectValuesFromMethod("people", user.people as any, serializePerson);
            writer.writeObjectValueFromMethod("photo", user.photo as any, serializeProfilePhoto);
            writer.writeCollectionOfObjectValuesFromMethod("photos", user.photos as any, serializeProfilePhoto);
            writer.writeObjectValueFromMethod("planner", user.planner as any, serializePlannerUser);
            writer.writeStringValue("postalCode", user.postalCode);
            writer.writeStringValue("preferredDataLocation", user.preferredDataLocation);
            writer.writeStringValue("preferredLanguage", user.preferredLanguage);
            writer.writeStringValue("preferredName", user.preferredName);
            writer.writeObjectValueFromMethod("presence", user.presence as any, serializePresence);
            writer.writeCollectionOfObjectValuesFromMethod("provisionedPlans", user.provisionedPlans as any, serializeProvisionedPlan);
            writer.writeCollectionOfPrimitiveValues<string>("proxyAddresses", user.proxyAddresses);
            writer.writeCollectionOfObjectValuesFromMethod("registeredDevices", user.registeredDevices as any, serializeDirectoryObject);
            writer.writeCollectionOfPrimitiveValues<string>("responsibilities", user.responsibilities);
            writer.writeCollectionOfPrimitiveValues<string>("schools", user.schools);
            writer.writeCollectionOfObjectValuesFromMethod("scopedRoleMemberOf", user.scopedRoleMemberOf as any, serializeScopedRoleMembership);
            writer.writeStringValue("securityIdentifier", user.securityIdentifier);
            writer.writeObjectValueFromMethod("settings", user.settings as any, serializeUserSettings);
            writer.writeBooleanValue("showInAddressList", user.showInAddressList);
            writer.writeDateValue("signInSessionsValidFromDateTime", user.signInSessionsValidFromDateTime);
            writer.writeCollectionOfPrimitiveValues<string>("skills", user.skills);
            writer.writeStringValue("state", user.state);
            writer.writeStringValue("streetAddress", user.streetAddress);
            writer.writeStringValue("surname", user.surname);
            writer.writeObjectValueFromMethod("teamwork", user.teamwork as any, serializeUserTeamwork);
            writer.writeObjectValueFromMethod("todo", user.todo as any, serializeTodo);
            writer.writeCollectionOfObjectValuesFromMethod("transitiveMemberOf", user.transitiveMemberOf as any, serializeDirectoryObject);
            writer.writeStringValue("usageLocation", user.usageLocation);
            writer.writeStringValue("userPrincipalName", user.userPrincipalName);
            writer.writeStringValue("userType", user.userType);
}
