import {AlertFeedback} from './alertFeedback';
import {AlertSeverity} from './alertSeverity';
import {AlertStatus} from './alertStatus';
import {Alert} from './index';
import {serializeAlertDetection} from './serializeAlertDetection';
import {serializeAlertHistoryState} from './serializeAlertHistoryState';
import {serializeAlertTrigger} from './serializeAlertTrigger';
import {serializeCloudAppSecurityState} from './serializeCloudAppSecurityState';
import {serializeEntity} from './serializeEntity';
import {serializeFileSecurityState} from './serializeFileSecurityState';
import {serializeHostSecurityState} from './serializeHostSecurityState';
import {serializeInvestigationSecurityState} from './serializeInvestigationSecurityState';
import {serializeMalwareState} from './serializeMalwareState';
import {serializeMessageSecurityState} from './serializeMessageSecurityState';
import {serializeNetworkConnection} from './serializeNetworkConnection';
import {serializeProcess} from './serializeProcess';
import {serializeRegistryKeyState} from './serializeRegistryKeyState';
import {serializeSecurityResource} from './serializeSecurityResource';
import {serializeSecurityVendorInformation} from './serializeSecurityVendorInformation';
import {serializeUriClickSecurityState} from './serializeUriClickSecurityState';
import {serializeUserSecurityState} from './serializeUserSecurityState';
import {serializeVulnerabilityState} from './serializeVulnerabilityState';
import {Parsable, ParseNode, SerializationWriter} from '@microsoft/kiota-abstractions';

export function serializeAlert(writer: SerializationWriter, alert: Alert | undefined = {}) : void {
        serializeEntity(writer, alert)
            writer.writeStringValue("activityGroupName", alert.activityGroupName);
            writer.writeCollectionOfObjectValuesFromMethod("alertDetections", alert.alertDetections as any, serializeAlertDetection);
            writer.writeStringValue("assignedTo", alert.assignedTo);
            writer.writeStringValue("azureSubscriptionId", alert.azureSubscriptionId);
            writer.writeStringValue("azureTenantId", alert.azureTenantId);
            writer.writeStringValue("category", alert.category);
            writer.writeDateValue("closedDateTime", alert.closedDateTime);
            writer.writeCollectionOfObjectValuesFromMethod("cloudAppStates", alert.cloudAppStates as any, serializeCloudAppSecurityState);
            writer.writeCollectionOfPrimitiveValues<string>("comments", alert.comments);
            writer.writeNumberValue("confidence", alert.confidence);
            writer.writeDateValue("createdDateTime", alert.createdDateTime);
            writer.writeStringValue("description", alert.description);
            writer.writeCollectionOfPrimitiveValues<string>("detectionIds", alert.detectionIds);
            writer.writeDateValue("eventDateTime", alert.eventDateTime);
            writer.writeEnumValue<AlertFeedback>("feedback", alert.feedback);
            writer.writeCollectionOfObjectValuesFromMethod("fileStates", alert.fileStates as any, serializeFileSecurityState);
            writer.writeCollectionOfObjectValuesFromMethod("historyStates", alert.historyStates as any, serializeAlertHistoryState);
            writer.writeCollectionOfObjectValuesFromMethod("hostStates", alert.hostStates as any, serializeHostSecurityState);
            writer.writeCollectionOfPrimitiveValues<string>("incidentIds", alert.incidentIds);
            writer.writeCollectionOfObjectValuesFromMethod("investigationSecurityStates", alert.investigationSecurityStates as any, serializeInvestigationSecurityState);
            writer.writeDateValue("lastEventDateTime", alert.lastEventDateTime);
            writer.writeDateValue("lastModifiedDateTime", alert.lastModifiedDateTime);
            writer.writeCollectionOfObjectValuesFromMethod("malwareStates", alert.malwareStates as any, serializeMalwareState);
            writer.writeCollectionOfObjectValuesFromMethod("messageSecurityStates", alert.messageSecurityStates as any, serializeMessageSecurityState);
            writer.writeCollectionOfObjectValuesFromMethod("networkConnections", alert.networkConnections as any, serializeNetworkConnection);
            writer.writeCollectionOfObjectValuesFromMethod("processes", alert.processes as any, serializeProcess);
            writer.writeCollectionOfPrimitiveValues<string>("recommendedActions", alert.recommendedActions);
            writer.writeCollectionOfObjectValuesFromMethod("registryKeyStates", alert.registryKeyStates as any, serializeRegistryKeyState);
            writer.writeCollectionOfObjectValuesFromMethod("securityResources", alert.securityResources as any, serializeSecurityResource);
            writer.writeEnumValue<AlertSeverity>("severity", alert.severity);
            writer.writeCollectionOfPrimitiveValues<string>("sourceMaterials", alert.sourceMaterials);
            writer.writeEnumValue<AlertStatus>("status", alert.status);
            writer.writeCollectionOfPrimitiveValues<string>("tags", alert.tags);
            writer.writeStringValue("title", alert.title);
            writer.writeCollectionOfObjectValuesFromMethod("triggers", alert.triggers as any, serializeAlertTrigger);
            writer.writeCollectionOfObjectValuesFromMethod("uriClickSecurityStates", alert.uriClickSecurityStates as any, serializeUriClickSecurityState);
            writer.writeCollectionOfObjectValuesFromMethod("userStates", alert.userStates as any, serializeUserSecurityState);
            writer.writeObjectValueFromMethod("vendorInformation", alert.vendorInformation as any, serializeSecurityVendorInformation);
            writer.writeCollectionOfObjectValuesFromMethod("vulnerabilityStates", alert.vulnerabilityStates as any, serializeVulnerabilityState);
}
