import {ItemFacet, LocaleInfo} from './index';
import {Parsable} from '@microsoft/kiota-abstractions';

export interface UserAccountInformation extends ItemFacet, Partial<Parsable> {
    /** Shows the age group of user. Allowed values null, minor, notAdult and adult are generated by the directory and cannot be changed. */
    ageGroup?: string;
    /** Contains the two-character country code associated with the users account. */
    countryCode?: string;
    /** The preferredLanguageTag property */
    preferredLanguageTag?: LocaleInfo;
    /** The user principal name (UPN) of the user associated with the account. */
    userPrincipalName?: string;
}
